/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.7.4-335
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import {
    
    callFunction,
    registerService,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v3.js';


// Services


// Functions
 
export type CreateResourceResult = [string | null, string[]]
export function createResource(
    label: string,
    config?: {ttl?: number}
): Promise<CreateResourceResult>;

export function createResource(
    peer: FluencePeer,
    label: string,
    config?: {ttl?: number}
): Promise<CreateResourceResult>;

